stages:
  - nox
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PATIENT_ABM_DIR: "$CI_PROJECT_DIR"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
# Hence we keep the .nox dir which contains the venv to run the tests
cache:
  paths:
    - .cache/pip
    - .nox/

nox:
  image: python:latest
  stage: nox
  before_script:
    - python -V
    - pip install -U nox
  script:
    - nox -r # make sure to use cached venv
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

# This jobs pushes the package to artifactory, the internal package index
# i.e. allows installation via `pip install patient_abm`
# By default, it is only run on *tagged* commits
build-and-push:
  only:
    - tags
    # - master # uncomment if all commits in master should be pushed
  image: python:3.8
  stage: deploy
  script:
    - pip install twine
    - python setup.py bdist_wheel
    - twine upload dist/* --verbose

# This jobs creates and hosts the package documention
# By default, it is only run on *tagged* commits
pages:
  image: python:3.8
  stage: deploy
  script:
    - pip install -U sphinx faculty-sphinx-theme
    - pip install .
    - make -C docs html
    - mv build/sphinx/html/ public/
  artifacts:
    paths:
      - public
  only:
    - tags
    # - master # uncomment if all commits in master should create docs
